config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: 'static_pages#top'
  resources :users, only: %i[new create]
  # resources :user_sessions, only: [:new, :create, :destroy], as: :login
  resources :codes, only: %i[index new create show edit update destroy] do
    #favoriteを追加
    resource :favorite, only: [:create, :destroy]
    collection do
      get 'favorites'
      get 'my_codes'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'terms_of_service', to: 'static_pages#terms_of_service'
end

app/models/code.rb
class Code < ApplicationRecord
  validates :title, presence: true, length: { maximum: 20 }
  enum is_public: { public: 0 , private: 1 }, _prefix: true

  validate :validation_empty_code

  belongs_to :user
  has_many :favorites, dependent: :destroy

  mount_uploader :image, ImageUploader
  before_destroy :remove_image

  has_many :code_tags, dependent: :destroy
  has_many :tags, through: :code_tags

  def save_tags(code_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - code_tags
    new_tags = code_tags - current_tags

    # 古いタグを削除
    old_tags.each do |old_tag|
      self.tags.delete Tag.find_by(tag_name: old_tag)
    end

    # 新しいタグを追加
    new_tags.each do |new_tag|
      add_tag = Tag.find_or_create_by(tag_name: new_tag)
      self.tags << add_tag unless self.tags.include?(add_tag)
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[title]
  end

  def self.ransackable_associations(auth_object = nil)
    ["tags", "user"]
  end

  def validation_empty_code
    if body_html.blank? && body_css.blank? && body_js.blank?
      errors.add(:base, "コードを入力してください")
    end
  end

  private
  def remove_image
    image.remove!
  rescue Exception => e
    logger.error(e.message)
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :private_code_access?, only: [:show, :edit]
  skip_before_action :authenticate_user!, only: [:index, :show, :edit]
  before_action :redirect_unless_owner, only: [:edit]

  def index
    # @codes = Code.eager_load(:user)

    @q = Code.ransack(params[:q])
    @codes = @q.result(distinct: true).eager_load(:user)

    @codes = if user_signed_in?
               @codes.where(is_public: "public").or(@codes.where(user_id: current_user.id))
             else
               @codes.where(is_public: "public")
             end

    order = params[:old] ? :asc : :desc
    @codes = @codes.order(created_at: order).page(params[:page]).per(12)
  end

  def show
    @code = Code.find(params[:id])
    @favorite = current_user.favorites.find_by(code_id: @code.id) if user_signed_in?
  end

  def new
    @code = Code.new
  end

  def edit
    @code = Code.find(params[:id])
    @favorite = current_user.favorites.find_by(code_id: @code.id) if user_signed_in?
    @tag_names = @code.tags.pluck(:tag_name).join(',')
  end

  def create
    @code = Code.new(code_params)
    @code.user = current_user
    tag_list = params[:code][:tag_name].split(',')
    if @code.save
      @code.save_tags(tag_list)
      flash[:notice] = t('flash.code.create')
      redirect_to codes_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @code = Code.find(params[:id])
    tag_list = params[:code][:tag_name].split(',')
    if @code.update(code_params)
      @code.save_tags(tag_list)
      flash[:notice] = t('flash.code.update')
      redirect_back(fallback_location: codes_path)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @code = Code.find(params[:id])
    @code.destroy!
    flash[:notice] = t('flash.code.destroy')
    redirect_to codes_path
  end

  def favorites
    @codes = current_user.favorites.map(&:code)
    @codes = Code.where(id: @codes.map(&:id)).eager_load(:user)

    if user_signed_in?
      @codes = @codes.where(is_public: "public").or(@codes.where(user_id: current_user.id))
    else
      @codes = @codes.where(is_public: "public")
    end

    order = params[:old] ? :asc : :desc
    @q = @codes.ransack(params[:q])
    @codes = @codes.order(created_at: order).page(params[:page]).per(16)

    render :index
  end

  def my_codes
    @codes = current_user.codes.eager_load(:user)
    if user_signed_in?
      @codes = @codes.where(is_public: "public").or(@codes.where(user_id: current_user.id))
    else
      @codes = @codes.where(is_public: "public")
    end

    order = params[:old] ? :asc : :desc
    @q = @codes.ransack(params[:q])
    @codes = @codes.order(created_at: order).page(params[:page]).per(16)
    render :index
  end

  private

  def code_params
    # is_publicをintegerに変換してparamsにセットする
    params[:code][:is_public] = params[:code][:is_public].to_i if params[:code][:is_public]
    params.require(:code).permit(:title, :body_html, :body_css, :body_js, :is_public, :image, :tag_names)
  end

  def user_owns_code?(code)
    code.user == current_user
  end

  def private_code_access?
    @code = Code.find(params[:id])
    if @code.is_public == "private"  && !user_owns_code?(@code)
      flash[:alert] = t('flash.code.private')
      redirect_to codes_path
    end
  end

  # 他人のコードを表示する場合は、詳細ページにリダイレクトする
  def redirect_unless_owner
    @code = Code.find(params[:id])
    redirect_to code_path(@code) unless user_owns_code?(@code)
  end

end

app/helpers/codes_helper.rb
module CodesHelper
  def private_check(code)
    if code.is_public == "public"
      return false
    else
      return true
    end
  end
end

app/views/codes/_editorComponent.html.erb
<div class="flex my-4 tb:flex-col">
  <%# // タブの切り替え %>
  <div role="tablist" class="tabs tabs-lifted flex-1 grid grid-cols-[auto_auto_1fr_auto] place-content-start">
    <input
      type="radio"
      name="my_tabs_2"
      role="tab"
      class="tab bg-base-100 [--tab-bg:#333333] checked:text-white csustom-tag-width"
      id="HTML_tab"
      aria-label="HTML"
      checked="checked"
      />
    <div role="tabpanel" class="tab-content bg-customGray border-base-300 rounded-box">
      <div id="editor_HTML" class=""></div> <%# HTML_editor挿入位置 %>
    </div>

    <input
      type="radio"
      name="my_tabs_2"
      role="tab"
      class="tab bg-base-100 [--tab-bg:#333333] checked:text-white csustom-tag-width"
      id="CSS_tab"
      aria-label="CSS"
      />
    <div role="tabpanel" class="tab-content bg-customGray border-base-300 rounded-box">
      <div id="editor_CSS" class=""></div> <%# CSS_editor挿入位置 %>
    </div>

    <input
      type="radio"
      name="my_tabs_2"
      role="tab"
      class="tab bg-base-100 [--tab-bg:#333333] checked:text-white csustom-tag-width"
      id="JS_tab"
      aria-label="JS"
      />
    <div role="tabpanel" class="tab-content bg-customGray border-base-300 rounded-box">
      <div id="editor_JS" class=""></div> <%# JS_editor挿入位置 %>
    </div>

    <label class="flex mr-4 items-center h-8 cursor-pointer px-2 tb:mr-2" data-action="click->code-title-edit#tailwind">
      <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 128 128" fill="#38bdf8" class="mr-1" id="tailwindIcon"><path d="M64.004 25.602c-17.067 0-27.73 8.53-32 25.597 6.398-8.531 13.867-11.73 22.398-9.597 4.871 1.214 8.352 4.746 12.207 8.66C72.883 56.629 80.145 64 96.004 64c17.066 0 27.73-8.531 32-25.602-6.399 8.536-13.867 11.735-22.399 9.602-4.87-1.215-8.347-4.746-12.207-8.66-6.27-6.367-13.53-13.738-29.394-13.738zM32.004 64c-17.066 0-27.73 8.531-32 25.602C6.402 81.066 13.87 77.867 22.402 80c4.871 1.215 8.352 4.746 12.207 8.66 6.274 6.367 13.536 13.738 29.395 13.738 17.066 0 27.73-8.53 32-25.597-6.399 8.531-13.867 11.73-22.399 9.597-4.87-1.214-8.347-4.746-12.207-8.66C55.128 71.371 47.868 64 32.004 64zm0 0"/></svg>
      <input type="checkbox" id="tailwindCheck" class="toggle toggle-sm toggle-info tb:hidden" checked="checked" />
    </label>
    <button class="justify-self-end h-8 place-content-center flex items-center hover:opacity-50 cursor-copy tb:px-2" id="copyBtn">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="20" viewBox="0 0 18 20" fill="currentColor" class="opacity-70 text-black">
        <path d="M12.75 17.5V19.0625C12.75 19.5803 12.3303 20 11.8125 20H1.1875C0.669727 20 0.25 19.5803 0.25 19.0625V4.6875C0.25 4.16973 0.669727 3.75 1.1875 3.75H4V15.3125C4 16.5187 4.98129 17.5 6.1875 17.5H12.75ZM12.75 4.0625V0H6.1875C5.66973 0 5.25 0.419727 5.25 0.9375V15.3125C5.25 15.8303 5.66973 16.25 6.1875 16.25H16.8125C17.3303 16.25 17.75 15.8303 17.75 15.3125V5H13.6875C13.1719 5 12.75 4.57812 12.75 4.0625ZM17.4754 2.85043L14.8996 0.27457C14.7238 0.0987666 14.4853 1.29998e-06 14.2367 0L14 0V3.75H17.75V3.51332C17.75 3.26469 17.6512 3.02624 17.4754 2.85043Z"/>
      </svg>
      <span class="items-center px-2 tb:hidden">Copy</span>
    </button>
    <div class="justify-self-end h-8 place-content-center flex items-center hidden" id="copiedText">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 25 25" fill="none">
        <path d="M8.4911 21.4554L0.366101 13.3304C-0.122034 12.8422 -0.122034 12.0508 0.366101 11.5626L2.13383 9.79481C2.62196 9.30663 3.41346 9.30663 3.9016 9.79481L9.37499 15.2682L21.0984 3.54481C21.5865 3.05668 22.378 3.05668 22.8662 3.54481L24.6339 5.31259C25.122 5.80072 25.122 6.59218 24.6339 7.08036L10.2589 21.4554C9.77069 21.9435 8.97924 21.9435 8.4911 21.4554Z" fill="#3BC85A"/>
      </svg>
      <span class="items-center px-2 sp:hidden">Copied</span>
    </div>
  </div>
  <iframe id="live_frame" class="flex-1 bg-white border-2 border-customGray mt-8 overlay-active"></iframe>
</div>

app/views/codes/_scriptForIframe.erb
<script>

window.update_live_frame = function () {
  const html_editor_value = document.getElementById("editorSource_HTML").value;
  const css_editor_value = document.getElementById("editorSource_CSS").value;
  const tailwindCheck = document.getElementById("tailwindCheck");

  if (live_frame && live_frame.contentWindow && live_frame.contentWindow.document) {
    live_frame.contentWindow.document.body.innerHTML = html_editor_value;
    if (tailwindCheck.checked) {
    live_frame.contentWindow.document.head.innerHTML =
      '<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">';
    live_frame.contentWindow.document.head.innerHTML += `<style>${css_editor_value}</style>`;
    }else{
    live_frame.contentWindow.document.head.innerHTML = `<style>${css_editor_value}</style>`;
    }
    live_frame.contentWindow.document.documentElement.classList.add("light");
    live_frame.contentWindow.document.body.classList.add(
      "bg-white",
      "border-2",
      "border-customGray",
      "p-4"
    );
  }
};

// tailwind の付け外し
if (typeof tailwindChecks === 'undefined') {
    var tailwindChecks = function () {
  const tailwindIcon = document.getElementById("tailwindIcon");
  const tailwindCheck = document.getElementById("tailwindCheck");

  const css_editor_value = document.getElementById("editorSource_CSS").value;

    if (!tailwindCheck.checked) {
      tailwindIcon.setAttribute("fill", "#333333");
      tailwindIcon.classList.add("opacity-70");
      live_frame.contentWindow.document.head.innerHTML = `<style>${css_editor_value}</style>`;
    } else {
      tailwindIcon.setAttribute("fill", "#38bdf8");
      live_frame.contentWindow.document.head.innerHTML +=
        '<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">';

    }
  };
};
document.getElementById("tailwindCheck").addEventListener("click", tailwindChecks);

</script>

app/views/codes/_showForm.html.erb
  <div class="flex items-bottom items-baseline">
    <h2 id="code_title" class="mt-10 text-4xl pr-4"><%= @code.title %></h2>
  </div>
  <% if controller.action_name != "new" %>
    <p class="pt-1">Created by <span class="underline"><%= "#{@code.user.name} (##{@code.user_id})" %></span></p>
  <% end %>
  <%# // タグの登録 %>
  <div class="flex justify-between items-center">
    <div class="card-actions justify-start mt-2">
      <% if @code.tags.present? %>
        <% @code.tags.each do |tag| %>
          <div class="badge badge-neutral"><%= tag.tag_name %></div>
        <% end %>
      <% end %>
    </div>
    <div class="flex gap-2">
      <% unless action_name == "new" %>
        <%= turbo_frame_tag "favorite_button" do %>
        <% if current_user != nil %>
          <% if @favorite == nil %>
            <%# // お気に入りボタン %>
            <%= link_to code_favorite_path(model), class:"btn h-10 min-h-10 flex bg-gray-200 px-3", data: { turbo_method: :post}, remote:true do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 25 25" fill="#333333">
              <g clip-path="url(#clip0_88_301)">
                <path d="M22.5738 3.49576C19.8981 1.21549 15.9186 1.62564 13.4625 4.15982L12.5006 5.15104L11.5387 4.15982C9.08751 1.62564 5.10314 1.21549 2.42736 3.49576C-0.639049 6.11295 -0.800182 10.8102 1.94396 13.6471L11.3922 23.403C12.0026 24.0329 12.9938 24.0329 13.6041 23.403L23.0524 13.6471C25.8014 10.8102 25.6402 6.11295 22.5738 3.49576Z"/>
              </g>
            </svg>
            <% end %>
          <% else %>
            <%# // お気に入り削除ボタン %>
            <%= link_to code_favorite_path(model), class:"btn h-10 min-h-10 flex bg-gray-200 px-3", data: { turbo_method: :delete} do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 25 25" fill="#F4858A">
              <g clip-path="url(#clip0_88_301)">
                <path d="M22.5738 3.49576C19.8981 1.21549 15.9186 1.62564 13.4625 4.15982L12.5006 5.15104L11.5387 4.15982C9.08751 1.62564 5.10314 1.21549 2.42736 3.49576C-0.639049 6.11295 -0.800182 10.8102 1.94396 13.6471L11.3922 23.403C12.0026 24.0329 12.9938 24.0329 13.6041 23.403L23.0524 13.6471C25.8014 10.8102 25.6402 6.11295 22.5738 3.49576Z"/>
              </g>
            </svg>
            <% end %>
          <% end %>
          <% end %>
        <% end %>
        <%# // Xシェアボタン %>
        <%= link_to "https://x.com/intent/tweet?url=#{ request.url }&text=【#{ @code.title}】%0a 素敵なコードを共有します!&hashtags=iCode", target: '_blank', class:"btn h-10 min-h-10 flex bg-gray-200 px-3" do %>
          <svg width="1200" height="1227" viewBox="0 0 1200 1227" fill="#333333" xmlns="http://www.w3.org/2000/svg" class="w-4 h-4">
          <path d="M714.163 519.284L1160.89 0H1055.03L667.137 450.887L357.328 0H0L468.492 681.821L0 1226.37H105.866L515.491 750.218L842.672 1226.37H1200L714.137 519.284H714.163ZM569.165 687.828L521.697 619.934L144.011 79.6944H306.615L611.412 515.685L658.88 583.579L1055.08 1150.3H892.476L569.165 687.854V687.828Z"/>
          </svg>
        <% end %>
      <% end %>
      <% if controller.action_name == "edit" %>
        <%# // 削除ボタン %>
        <%= link_to code_path(model), class: "btn btn-error h-10 min-h-10 hover:opacity-70 px-3", data: { turbo_method: :delete, turbo_confirm: t('message.confirm_delete')} do%>
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 25 25" fill="#333333">
            <g clip-path="url(#clip0_88_305)">
              <path d="M22.6562 1.56251H16.7969L16.3379 0.649423C16.2407 0.454215 16.0909 0.29001 15.9054 0.175281C15.72 0.0605526 15.5062 -0.00014785 15.2881 8.5609e-06H9.70703C9.48944 -0.000827891 9.27602 0.0596463 9.09121 0.174503C8.90641 0.289359 8.75769 0.453951 8.66211 0.649423L8.20312 1.56251H2.34375C2.13655 1.56251 1.93784 1.64482 1.79132 1.79133C1.64481 1.93784 1.5625 2.13656 1.5625 2.34376L1.5625 3.90626C1.5625 4.11346 1.64481 4.31217 1.79132 4.45869C1.93784 4.6052 2.13655 4.68751 2.34375 4.68751H22.6562C22.8635 4.68751 23.0622 4.6052 23.2087 4.45869C23.3552 4.31217 23.4375 4.11346 23.4375 3.90626V2.34376C23.4375 2.13656 23.3552 1.93784 23.2087 1.79133C23.0622 1.64482 22.8635 1.56251 22.6562 1.56251ZM4.16016 22.8027C4.19742 23.3978 4.46004 23.9562 4.89456 24.3644C5.32908 24.7727 5.90283 24.9999 6.49902 25H18.501C19.0972 24.9999 19.6709 24.7727 20.1054 24.3644C20.54 23.9562 20.8026 23.3978 20.8398 22.8027L21.875 6.25001H3.125L4.16016 22.8027Z"/>
            </g>
          </svg>
        <% end %>
      <% end %>
    </div>
  </div>
  <%# // HTMLエディタ %>
  <div>
    <%= form_with model: model do |form| %>
      <%= form.text_area :body_html, id: "editorSource_HTML", class: "hidden" %>
      <%= form.text_area :body_css, id: "editorSource_CSS", class: "hidden" %>
      <%= form.text_area :body_js, id: "editorSource_JS", class: "hidden" %>
    <% end %>
  </div>

app/views/codes/edit.html.erb
<%= render 'devise/shared/error_messages', resource: @code %>
<div class="container mx-auto px-5">
  <%= render partial: 'codes/editForm', locals: { model: @code } %>
  <%= render partial: 'codes/editorComponent' %>
</div>

<%= render'codes/scriptForIframe' %>
<% assign_meta_tags title: "#{@code.title}",
                    image: @code.image_url
                    %>

app/views/codes/new.html.erb
<%= render 'devise/shared/error_messages', resource: @code %>
<div class="container mx-auto px-5">
  <%= render partial: 'codes/editForm', locals: { model: @code } %>
  <%= render partial: 'codes/editorComponent' %>
</div>

<%= render'codes/scriptForIframe' %>

app/views/codes/show.html.erb
<%= render 'devise/shared/error_messages', resource: @code %>
<div class="container mx-auto px-5" data-controller="read-only-editor">
  <%= render partial: 'codes/showForm', locals: { model: @code } %>
  <%= render partial: 'codes/editorComponent' %>
</div>

<%= render'codes/scriptForIframe' %>
<% assign_meta_tags title: "#{@code.title}",
                    image: @code.image_url
                    %>