config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  root to: 'static_pages#top'
  resources :users, only: %i[new create]
  # resources :user_sessions, only: [:new, :create, :destroy], as: :login
  resources :codes, only: %i[index new create show edit update destroy] do
    #favoriteを追加
    resource :favorite, only: [:create, :destroy]
    collection do
      get 'favorites'
      get 'my_codes'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'terms_of_service', to: 'static_pages#terms_of_service'
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="<%= flash_background_color(message_type) %> border-l-4  px-4 py-2 rounded-md mb-4 container w-100 mx-auto">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="foot_gap footer footer-center bg-gray-200 text-base-content px-10 py-4 mt-auto w-100">
  <div class="flex w-100 justify-between container px-5 sp:px-0 width-adj">
    <nav class="grid grid-flow-col gap-5 sp:grid-flow-row sp:text-left sp:gap-3">
      <%= link_to t('footer.contact'), "https://forms.gle/bCZhTi846ejLjt2D6", class: "link link-hover" %>
      <%= link_to t('footer.terms'), terms_of_service_path, class: "link link-hover" %>
      <%= link_to t('footer.privacy'), "https://www.kiyac.app/privacypolicy/XOe5n8fN4DaGCrrng7UW", class: "link link-hover" %>
    </nav>
    <nav>
      <div class="grid grid-flow-col gap-4">
        <%= link_to "https://x.com/kamteyaso", target: "_blank" do %>
          <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg" class="hover:opacity-70">
            <g id="mage:x">
              <path id="Vector" d="M29.585 5H34.6966L23.53 17.7083L36.6666 35H26.38L18.325 24.5117L9.10665 35H3.98998L15.935 21.4083L3.33331 5H13.88L21.1633 14.5867L29.585 5ZM27.7916 31.9533H30.625L12.34 7.88667H9.29998L27.7916 31.9533Z" fill="#333333"/>
            </g>
          </svg>
        <% end %>
        <%= link_to "https://github.com/kame82", target: "_blank" do %>
          <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg" class="hover:opacity-70">
            <g id="mdi:github">
              <path id="Vector" d="M20 3.33337C17.8113 3.33337 15.644 3.76447 13.6219 4.60205C11.5998 5.43963 9.76251 6.66728 8.21487 8.21493C5.08926 11.3405 3.33331 15.5798 3.33331 20C3.33331 27.3667 8.11665 33.6167 14.7333 35.8334C15.5666 35.9667 15.8333 35.45 15.8333 35V32.1834C11.2166 33.1834 10.2333 29.95 10.2333 29.95C9.46665 28.0167 8.38331 27.5 8.38331 27.5C6.86665 26.4667 8.49998 26.5 8.49998 26.5C10.1666 26.6167 11.05 28.2167 11.05 28.2167C12.5 30.75 14.95 30 15.9 29.6C16.05 28.5167 16.4833 27.7834 16.95 27.3667C13.25 26.95 9.36665 25.5167 9.36665 19.1667C9.36665 17.3167 9.99998 15.8334 11.0833 14.65C10.9166 14.2334 10.3333 12.5 11.25 10.25C11.25 10.25 12.65 9.80004 15.8333 11.95C17.15 11.5834 18.5833 11.4 20 11.4C21.4166 11.4 22.85 11.5834 24.1666 11.95C27.35 9.80004 28.75 10.25 28.75 10.25C29.6666 12.5 29.0833 14.2334 28.9166 14.65C30 15.8334 30.6333 17.3167 30.6333 19.1667C30.6333 25.5334 26.7333 26.9334 23.0166 27.35C23.6166 27.8667 24.1666 28.8834 24.1666 30.4334V35C24.1666 35.45 24.4333 35.9834 25.2833 35.8334C31.9 33.6 36.6666 27.3667 36.6666 20C36.6666 17.8113 36.2355 15.6441 35.398 13.622C34.5604 11.5999 33.3327 9.76257 31.7851 8.21493C30.2374 6.66728 28.4001 5.43963 26.378 4.60205C24.3559 3.76447 22.1887 3.33337 20 3.33337Z" fill="#333333"/>
            </g>
          </svg>
        <% end %>
      </div>
      <p>Contact me</p>
    </nav>
  </div>
  <aside>
    <small>Copyright 2024 - All right reserved by Tsukamo Ltd</small>
  </aside>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-gray-950">
  <div class="container px-5 py-5 flex justify-between mx-auto width-adj">
    <h1><%=link_to "iCode", root_path, class: "text-4xl sp:text-2xl font-bold" %></h1>
    <div class="flex gap-x-7 items-center tb:gap-x-4">
      <%= link_to t('header.code_index'), codes_path, class: "link link-hover" %>
      <% if user_signed_in? %>
        <div class="dropdown dropdown-hover dropdown-end">
          <div tabindex="0" class="cursor-pointer link-hover flex">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 25 25" fill="white">
              <g clip-path="url(#clip0_403_2)">
                <path d="M12.5 14.0625C16.3818 14.0625 19.5312 10.9131 19.5312 7.03125C19.5312 3.14941 16.3818 0 12.5 0C8.61816 0 5.46875 3.14941 5.46875 7.03125C5.46875 10.9131 8.61816 14.0625 12.5 14.0625ZM18.75 15.625H16.0596C14.9756 16.123 13.7695 16.4062 12.5 16.4062C11.2305 16.4062 10.0293 16.123 8.94043 15.625H6.25C2.79785 15.625 0 18.4229 0 21.875V22.6562C0 23.9502 1.0498 25 2.34375 25H22.6562C23.9502 25 25 23.9502 25 22.6562V21.875C25 18.4229 22.2021 15.625 18.75 15.625Z"/>
              </g>
            </svg>
            <span class="ml-2"><%= "#{current_user.name} (##{current_user.id})" %></span>
          </div>
          <ul tabindex="0" class="dropdown-content menu bg-white rounded-box z-[1] w-32 p-2 shadow border-black text-black border-solid border-2 pt-2">
            <li><%= link_to t('header.my_code'), my_codes_codes_path %></li>
            <li><%= link_to t('header.favorite'), favorites_codes_path %></li>
            <li><%= link_to t('header.logout'), destroy_user_session_path, data: {turbo_method: :delete}, class: "link link-hover text-red-500" %></li>
          </ul>
        </div>
      <% else %>
        <%= link_to t('header.login'), new_user_session_path ,class: "link link-hover" %>
        <%= link_to t('header.signup'), new_user_registration_path, class: "link link-hover" %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= show_meta_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body id="<%= "#{controller_name}_#{action_name}" %>" class="pb-28 sp:pb-44">
    <%= render "layouts/header" %>
    <!-- Flash message -->
    <div class="mt-20 flex flex-col h-full mx-auto width-adj">
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>